#version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: postgres_container
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: nanomarket_db
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
    volumes:
      - ./nanomarket_db_data:/var/lib/postgresql/data/pgdata
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    command: >
      postgres -c max_connections=1000
               -c shared_buffers=256MB
               -c effective_cache_size=768MB
               -c maintenance_work_mem=64MB
               -c checkpoint_completion_target=0.7
               -c wal_buffers=16MB
               -c default_statistics_target=100
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root -d root" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    tty: true
    stdin_open: true
    networks:
      - backend

  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ACCESS_KEY: minioaccesskey
      MINIO_SECRET_KEY: miniosecretkey
#      MINIO_BUCKETS: BrandImage, ProductImage
    ports:
      - "9000:9000"
    volumes:
      - ./minio_data:/data
    command: server /data
    restart: unless-stopped
    networks:
      - backend

  config-server:
    image: nanomarket/config-server:latest
    container_name: config-server
    build:
      context: ./ConfigServer
      dockerfile: Dockerfile
    volumes:
      - ./ConfigServer/src/main/resources/config:/app/config
    ports:
      - "8071:8071"
    networks:
      - backend
    environment:
#      - GIT_SSH_PRIVATE_KEY=${GIT_SSH_PRIVATE_KEY}
      - SPRING_PROFILES_ACTIVE=native

  eureka:
    image: nanomarket/eureka-server:latest
    container_name: eureka
    build:
      context: ./EurekaServer
      dockerfile: Dockerfile
    ports:
      - "8070:8070"
    depends_on:
      - config-server
    networks:
      - backend

  product-service:
    image: nanomarket/config-server:latest
    container_name: product-service
    build:
      context: ./ProductService
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - eureka
      - postgres
      - minio
    networks:
      - backend


volumes:
  nanomarket_db_data:
  minio_data:
networks:
  backend:
    driver: bridge
