spring:
  application:
    name: product-service
  config:
    import: configserver:http://localhost:8071
  profiles:
    active: dev
  liquibase:
    enabled: true
    contexts: dev
  cloud:
    config:
      fail-fast: true
      retry:
        max-interval: 10000
        max-attempts: 10
        initial-interval: 2000
        multiplier: 1.5
