spring:
  application:
    name: config-server
  profiles:
    active: git

  cloud:
    config:
      server:
#        native:
#          search-locations: file:/app/config
        #          search-locations: file:./src/main/resources/config
        git:
          uri: https://github.com/RylovK/nanomarket-config-repo.git

          clone-on-start: true
          search-paths: config
          default-label: main


server:
  port: 8071

management:
  endpoints:
    web:
      exposure:
        include: health,info