spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: file:./src/main/resources/config
#        git:
#          uri: git@github.com:RylovK/nanomarket-config-repo.git
#            #           private-key: ${GIT_SSH_PRIVATE_KEY}
#          clone-on-start: true
#          search-paths: config
        bootstrap: true
  profiles:
    active: native


server:
  port: 8071

management:
  endpoint:
    env:
      post:
        enabled: true
