# Используем официальный образ Maven для сборки приложения
FROM maven:3.8.5-eclipse-temurin-17 as builder

# Указываем рабочую директорию для сборки
WORKDIR /app

# Копируем pom.xml и все pom.xml из родительской папки проекта, чтобы сохранить кэш для зависимостей
COPY ../../pom.xml ../../
COPY pom.xml .

# Копируем исходный код модуля ConfigServer в контейнер
COPY src ./src

# Скачиваем зависимости и собираем модуль ConfigServer
RUN mvn clean package -DskipTests

# Второй этап: использование lightweight Java image для исполнения
FROM eclipse-temurin:17-jre-alpine

# Указываем рабочую директорию в контейнере
WORKDIR /app

# Копируем собранный JAR файл из предыдущего этапа
COPY --from=builder /app/target/configserver-*.jar app.jar

# Открываем порт, если требуется
#EXPOSE 8888

# Указываем команду для запуска приложения
ENTRYPOINT ["java", "-jar", "app.jar"]
